apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  rules:
    - host: llama.devopsfor.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-llama3-2-3b
                port:
                  number: 11434
  ingressClassName: nginx