apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3-2-3b
  namespace: llms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: llama3-2-3b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: llama3-2-3b
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.3.12
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - ollama
                  - run
                  - llama3.2:3b
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: 11434
              name: http
          resources:
            limits:
              memory: 8000Mi
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
              memory: 8000Mi
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama-data
      volumes:
        - emptyDir: {}
          name: ollama-data
      restartPolicy: Always
      dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: Service
metadata:
  name: service-llama3-2-3b
  namespace: llms
spec:
  selector:
    name: llama3-2-3b
  ports:
    - name: http
      port: 11434
      protocol: TCP
      targetPort: http
  type: ClusterIP